spring:
  application:
    name: travel-agency-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/travelagency
    username: postgres
    password: 1811
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/travelagency

server:
  port: 8090

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG